dataset:
  use_objlat: False
  filter_fn: bedroom
  dataset_dir: ./datasets/atiss_bedroom
  attr_dim: 43
  padded_length: 27
  num_class: 31

super_parameters:
  epochs: 1000
  batch_size: 128
  learning_rate: 0.0001
  weight_decay: 0.00001
  cuda: 0

save:
  save_folder: ./pretrained/atiss/


network: 
  type: atiss
  n_layers: 4
  n_heads: 8
  query_dimensions: 64
  value_dimensions: 64
  feed_forward_dimensions: 1024
  hidden2output_layer: "autoregressive_mlc"
  hidden_dims: 512
  with_extra_fc: false
  bbox_output: "autoregressive_mlc"
  n_mixtures: 10
  use_room_mask_as_features: true

training:
    splits: ["train", "val"]
    epochs: 10000
    steps_per_epoch: 500
    batch_size: 128
    save_frequency: 50
    optimizer: Adam
    lr: 0.0001
    weight_decay: 0.0

loss:
  beta: 0.25


logger:
    type: "wandb"
    project: "autoregressive_transformer"