model:
  type: sar
  depth: 16
  num_heads: 8
  mlp_ratio: 4.0
  drop_rate: 0.1
  attn_drop_rate: 0.1
  drop_path_rate: 0.2
  shared_aln: true
  norm_eps: 1e-6
  attn_l2_norm: False
  use_prior_cluster: False
  word_dim: 512

  feat_extractor: resnet18
  bottleneck : residual-vae
  quant:
    vq_beta: 1
    ema_decay: 0.95

  encoder:
    type: vqvae
    token_dim: 64
    encoder_depth: 6
    num_bottleneck : 25
    decoder_depth: 4
    num_recon: 25
    num_heads: 8
    num_embeddings: 512
    bottleneck : residual-vae
    use_codebook: true
    quant:
      vq_beta: 1
      ema_decay: 0.95
    pretrained_path: ./pretrained/vqvae/exp3_wi_residual_vq_wo_context_wo_ema_bedroom_lat64/vqvae.pth

dataset:
  filter_fn: bedroom
  dataset_dir: ./datasets/processed_bedroom
  use_objlat: true
  attr_dim: 107
  padded_length: 25

super_parameters:
  epochs: 2000
  batch_size: 128
  learning_rate: 0.0001
  weight_decay: 0.00001
  cuda: 0

save:
  save_folder: ./pretrained/sceneGPT/depth_16_worddim_1024_bedroom

text_condition: true
room_mask_condition: true